#!/bin/bash

export PATH=$PATH:~/.gem/ruby/2.1.0/bin/:~/maple17/bin
export _JAVA_AWT_WM_NONREPARENTING=1

sh ~/setroot.sh
touch ham-sandwish.txt

# xset -b

# xrdb ~/.Xresources

# xsetroot -cursor_name left_ptr

